name: exposed-dao
main: dev.h4kt.exposed.plugin.bukkit.ExposedDao
authors: [H4kt, JetBrains Team]
version: ${version}
depends: [kotlin-stdlib, kotlin-reflect, kotlinx-coroutines, exposed-core]
api-version: 1.13
