name: exposed-core
main: dev.h4kt.exposed.plugin.bukkit.ExposedCore
authors: [H4kt, JetBrains Team]
version: ${version}
api-version: "1.20"
dependencies:
  server:
    kotlin-stdlib:
      load: BEFORE
      required: true
      join-classpath: true
    kotlin-reflect:
      load: BEFORE
      required: false
      join-classpath: true
    kotlinx-coroutines:
      load: BEFORE
      required: false
      join-classpath: true
