name: kotlinx-datetime
main: dev.h4kt.kotlinx.plugin.bukkit.KotlinxDateTime
authors: [H4kt, JetBrains Team]
version: ${version}
api-version: "1.20"
dependencies:
  server:
    kotlin-stdlib:
      load: BEFORE
      required: true
      join-classpath: true
