name: kotlinx-serialization-json
main: io.h4kt.kotlinx.plugin.bukkit.KotlinxSerializationJson
authors: [H4kt, JetBrains Team]
version: {version}
depends: [kotlin-stdlib, kotlinx-serialization-core]
api-version: 1.13